/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_coinevo_coinevonet_CoinevonetVPN */

#ifndef _Included_network_coinevo_coinevonet_CoinevonetVPN
#define _Included_network_coinevo_coinevonet_CoinevonetVPN
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_coinevo_coinevonet_CoinevonetVPN
   * Method:    PacketSize
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_coinevo_coinevonet_CoinevonetVPN_PacketSize(JNIEnv *, jclass);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetVPN
   * Method:    Alloc
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_coinevo_coinevonet_CoinevonetVPN_Alloc(JNIEnv *, jclass);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetVPN
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_coinevo_coinevonet_CoinevonetVPN_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetVPN
   * Method:    Stop
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_network_coinevo_coinevonet_CoinevonetVPN_Stop(JNIEnv *, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetVPN
   * Method:    ReadPkt
   * Signature: (Ljava/nio/ByteBuffer;)I
   */
  JNIEXPORT jint JNICALL
  Java_network_coinevo_coinevonet_CoinevonetVPN_ReadPkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetVPN
   * Method:    WritePkt
   * Signature: (Ljava/nio/ByteBuffer;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_coinevo_coinevonet_CoinevonetVPN_WritePkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetVPN
   * Method:    SetInfo
   * Signature: (Lnetwork/coinevo/coinevonet/CoinevonetVPN/VPNInfo;)V
   */
  JNIEXPORT void JNICALL
  Java_network_coinevo_coinevonet_CoinevonetVPN_SetInfo(JNIEnv *, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
