/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_coinevo_coinevonet_CoinevonetVPN_VPNInfo */

#ifndef _Included_network_coinevo_coinevonet_CoinevonetVPN_VPNInfo
#define _Included_network_coinevo_coinevonet_CoinevonetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
