/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_coinevo_coinevonet_CoinevonetDaemon */

#ifndef _Included_network_coinevo_coinevonet_CoinevonetDaemon
#define _Included_network_coinevo_coinevonet_CoinevonetDaemon
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_coinevo_coinevonet_CoinevonetDaemon
   * Method:    Obtain
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_coinevo_coinevonet_CoinevonetDaemon_Obtain(JNIEnv *, jclass);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetDaemon
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_coinevo_coinevonet_CoinevonetDaemon_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetDaemon
   * Method:    Configure
   * Signature: (Lnetwork/coinevo/coinevonet/CoinevonetConfig;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_coinevo_coinevonet_CoinevonetDaemon_Configure(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetDaemon
   * Method:    Mainloop
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_coinevo_coinevonet_CoinevonetDaemon_Mainloop(JNIEnv *, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetDaemon
   * Method:    IsRunning
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_coinevo_coinevonet_CoinevonetDaemon_IsRunning(JNIEnv *, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetDaemon
   * Method:    Stop
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_coinevo_coinevonet_CoinevonetDaemon_Stop(JNIEnv *, jobject);

  /*
   * Class:     network_coinevo_coinevonet_CoinevonetDaemon
   * Method:    InjectVPN
   * Signature: (Lnetwork/coinevo/coinevonet/CoinevonetVPN;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_coinevo_coinevonet_CoinevonetDaemon_InjectVPN(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
