#!/bin/sh
echo "Running postinstall" > /tmp/coinevonet_postinstall.log

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

rm $HOME/.coinevonet/*.signed >> /tmp/coinevonet_postinstall.log
rm $HOME/.coinevonet/*.key >> /tmp/coinevonet_postinstall.log
rm $HOME/.coinevonet/*.private >> /tmp/coinevonet_postinstall.log
rm -fr $HOME/.coinevonet/netdb >> /tmp/coinevonet_postinstall.log

/usr/local/bin/coinevonet -g >> /tmp/coinevonet_postinstall.log

url="https://seed.coinevo.tech/bootstrap.signed"
echo "downloading $url" >> /tmp/coinevonet_postinstall.log
echo "to $HOME/.coinevonet/bootstrap.signed" >> /tmp/coinevonet_postinstall.log

# use temp file to not overrwrite existing bootstrap file on fail
tmp=/tmp/bootstrap.tmp

# MacOS does not have wget without homebrew but does have curl
# Rick also had indicated most BSDs have curl too
curl "$url" > "$tmp" && \
    (mv "$tmp" "$HOME/.coinevonet/bootstrap.signed" && echo "${GREEN}coinevonet successfully bootstrapped${NC}" >> /tmp/coinevonet_postinstall.log) \
        || echo "${RED}failed to download bootstrap from $url${NC}" >> /tmp/coinevonet_postinstall.log
rm -f "$tmp"

exit 0 # all good
