#!/bin/sh
echo "Running preinstall" > /tmp/coinevonet_preinstall.log
if [ ! -d "$HOME/.coinevonet" ]
then
  mkdir $HOME/.coinevonet >> /tmp/coinevonet_preinstall.log
fi
find $HOME/.coinevonet >> /tmp/coinevonet_preinstall.log
exit 0 # all good
