apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinevo-deployment
  labels:
    app: coinevo-svc-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coinevo-svc-node
  template:
    metadata:
      labels:
        app: coinevo-svc-node
    spec:
      containers:
      - name: coinevo-svc-node
        image: jaaff/coinevo-svc-kubernetes
        ports:
          - protocol: TCP
            port: 33330
            targetPort: 33330
          - protocol: TCP
            port: 33331
            targetPort: 33331
          - protocol: UDP
            port: 1090
            targetPort: 1090
          
