#!/bin/sh -e
setcap cap_net_admin,cap_net_bind_service=+eip /usr/bin/coinevonet || echo "failed to setcap coinevonet"
adduser --quiet --system --home /var/lib/coinevonet debian-coinevonet || echo "debian-coinevonet user not added"
